---
title: "ViralProduction_Workflow"
author: "Hisham M Shaikh"
date: '2022-06-17'
output: html_document
---

**1. Setting up working directory**\
\
\

**2. Installing libraries**\
\
We can simply source the `0_vp_source.R` script\

    source(0_vp_source.R)

\
\
**3. Extracting Counts from FCS files**\
\
The script, `1_input_data_counts.R`, reads the FCS files and extracts count information on the following:\
1. Total\
2. Total Bacteria\
3. Total Viruses\
4. HNA Bacteria\
5. LNA Bacteria\
6. V1 Viruses\
7. V2 Viruses\
8. V3 Viruses\
\
The output is saved as a `.csv` file\
\
\
**4. Data wrangling and metadata**\
\
The script, `2_data_wrangling_TE`, takes the input `.csv` file, adds the metadata,
and corrects for TE.\
The output of this is another `.csv` file.\
This `.csv` file can be used for plotting and extracting downstream information. \
\
\
**5. Generating Plots**\
Here we try to get an overview plot from the `.csv` generated in Step 4. \
We'll first generate a plot from averaged values for VP and VPC. We'll subtract VP from VPC
to calculate the Difference curve.\

df_avg_tp(NJ1) %>%
plots_lm_tp()

