---
title: "Viral Production in R"
output:
  html_notebook: default
  html_document:
    df_print: paged
  word_document: default
---
```
{
library(ggplot2)
}
```

**To do list:**

1. Set up lm plots\
  Different timepoint\
2. Set up VIPCAL plots



LM plots\
I will first try to build an LM plot for total viruses per time point combination
for all three replicates of VP.\




**Trying to recreate VIPCAL. And further adding the standard deviation command**\
We want the VIPCAL to only give out values if the negative SD is above the positive 
SD of previous time point


To idnetify the peaks we'll use the `findPeaks` and `findValleys` function FROM 
`quantmod` R package. Three considerations:\
1. It always gives the outcome as the value after the peak. Therfore it is important
to add a `-1` in the code. Or we define our own fucntion\
2. To identify the first timepoint as a valley, you'll have to add a timepoint before
and assign a really high value. Let's say `1E10`\
3. To identify the last time point as a peak, you'll have to to add a timepoint after
and assign a really low value. Let's say `-1E10`



Check the plots vs subgroups script for the function




Okay, so for modified VIPCAL, VP is estimated between a minima and the maxima that follows the minima
with the following criterion\
The mean-SD of the maxima > mean+SD of the minima. 

```{r echo=TRUE}
ggplot(data[2:7,], aes(Timepoints, VP_mean))+
  geom_point()+
  #geom_smooth()+
geom_line()+
  theme_minimal()+
  geom_errorbar(aes(ymin= VP_mean-VP_sd, ymax=VP_mean+VP_sd), width=.2,
                position=position_dodge(.9))
```

  
  
  
  
  
  Let's start again. \
  I have managed to do the following\
  1. Get counts for NJ1 data set- Bacteria, HNA, LNA, Viruses, V1, V2, V3\
  2. Correct for TE. Calculate means and SD. \
  3. Plot all, parents and subgroup plots for VP and VPC. \
  4. Calculate viral production for VIPCAL. with and without SD. \
  
  To do:\
  1. Plots for VIPCAL- VP, VPC and Diff together. **done**\
  2. LM and VIPCAL plots with sloughed off  time points. \
  3. viral production compared between LM, VIPCAL, VIPCAL-SD.\
  4. Bacterial production addition **done**\
  
  
  
  
4. Bacterial Production: net growth rate.\
We will observe generation time over 24 hours of incubation to understand when the
assay need to stop.\ 
We say \
Gross Bacterial Production = Net bacterial production + bacterial loss due to viral lysis 
+ bacterial loss due to grazing\
As we only have the the net growth rate, we will assume that the gross bacterial growth rate
is two times higher (or the factor for grazing) that next growth rate.\
We will then determine generation time, and the moment generation time based on net growth rate
reaches 12 hours, our assay stops. 12 hours and not 24 hours because GP = 2NP.\
But doing that dramatically increases the Vp in some cases. \


***Calculating Lytic Viral Production***\
1. **Linear regression:**\
  a. Three slopes (one per replicate). We then, average these slopes to get a VP, along with SD value.\
  b. Average the timepoints (with SD). One slope. **LYT-LM-SR** \
  *The only difference between 1a and 1b will be SD values.* **LYT-LM-AVG**\
2. **VIPCAL:**\
  a. Three values. One per replicate. Then average, and calculate SD **LYT-VCAL-SR**\
  b. One value, after averaging timepoints without SD **LYT-VCAL-AVG**\
3. **VIPCAL-SD:**\
  a. Three values. One per replicate. Then average, and calculate SD **LYT-VSD-SR**\
  b. One value, after averaging timepoints without SD **LYT-VSD-AVG**\

***Calculating Lysogenic Viral Production***\
1. **Linear Regression:**\
  a. Three slopes of VP, and VPC. Subtracting avg slopes Avg(SD) VPC - Avg(SD) VP. **LYS-LM-SR**\
  b. One slope of VP and VPC, each, after averaging timepoints. Then subtracting them. **LYS-LM-AVG**\
  *The only difference here would be SD values*\
2. **VIPCAL:**\
  a. Avg timepoints. Diff curve is calculated by subtracting av timepoints between VPC and VP.
  One curve. One value. NO SD. **LYS-VCAL-AVG**\
3. **VIPCAL-SD:**\
  a. Avg timepoints. Diff curve is calculated by subtracting avg timepoints between VPC and VP.
  You take into account the SD for calculating peaks. **LYS-VSD-AVG**\
\\

First, we can calculate viral production rates on separate replicate dataframe. 
I will have to create SR dataframe and Avg Dataframes from metadata, TE-corrected dataframe.\


\
\

**Viral Production SD time point sloughing**

**ATTEMPTING VIRAL PRODUCTION PLOTS**\
Steps:\
1. LM viral production Lytic T24.\
2. VIPCAL VP

